#:schema ../../schema/rfc.schema.json

[govctl]
id = "RFC-0004"
title = "Outbound Traps"
version = "0.1.0"
status = "normative"
phase = "stable"
owners = ["@Helge Penne"]
created = "2026-03-16"
updated = "2026-03-17"

[[sections]]
title = "Summary"

[[sections]]
title = "Specification"
clauses = ["clauses/C-TRAPS.toml"]

[[changelog]]
version = "0.1.0"
date = "2026-03-16"
notes = "Initial draft"
